// Generated by tools/generate_versions.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace cardbridge {

inline constexpr char kFirmwareVersion[] = "0.3.0";
inline constexpr uint32_t kFirmwareBuild = 8;
inline constexpr uint8_t kDeviceProtocolMajor = 2;
inline constexpr uint8_t kDeviceProtocolMinor = 1;
inline constexpr bool kSupportLegacyProtocol1 = true;
inline constexpr const char* kDeviceCapabilities[] = {
    "control.keys.v1",
    "audio.pcm16-16k.v1",
    "agents.snapshot.v1",
    "agents.phase.v1",
    "quota.v1",
};
inline constexpr size_t kDeviceCapabilityCount =
    sizeof(kDeviceCapabilities) / sizeof(kDeviceCapabilities[0]);

}  // namespace cardbridge
