// Generated by tools/pack_pet.py; do not hand-edit.
#pragma once

#include <Arduino.h>

namespace cardbridge::pet_assets {

constexpr uint8_t kFrameWidth = 72;
constexpr uint8_t kFrameHeight = 72;

enum class AnimationId : uint8_t { Idle, Failed, Waiting, Running, Review };

struct Frame {
  const uint8_t* data;
  uint16_t length;
  uint16_t durationMs;
};

struct Animation {
  const Frame* frames;
  uint8_t count;
};

extern const uint16_t kPalette[16];
const Animation& get(AnimationId id);

}  // namespace cardbridge::pet_assets
