// Generated by tools/pack_ui_background.py; do not hand-edit.
#pragma once

#include <Arduino.h>

namespace cardbridge::ui_background_asset {

constexpr uint16_t kWidth = 240;
constexpr uint16_t kHeight = 135;
extern const uint16_t kPixels[kWidth * kHeight];

}  // namespace cardbridge::ui_background_asset
