#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
VERSION_PATH = ROOT / "version.json"
SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")


def _load() -> dict[str, Any]:
    data = json.loads(VERSION_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("version.json must contain an object")
    for path in (
        ("release",),
        ("mac_app", "version"),
        ("bridge_agent", "version"),
        ("firmware", "version"),
        ("compatibility", "min_firmware"),
    ):
        value: object = data
        for key in path:
            if not isinstance(value, dict) or key not in value:
                raise ValueError(f"missing version field: {'.'.join(path)}")
            value = value[key]
        if not isinstance(value, str) or not SEMVER.fullmatch(value):
            raise ValueError(f"{'.'.join(path)} must be numeric SemVer")
    for section in ("mac_app", "bridge_agent", "firmware"):
        build = data.get(section, {}).get("build")
        if not isinstance(build, int) or build < 1:
            raise ValueError(f"{section}.build must be a positive integer")
    for section in ("agent_api", "device_protocol"):
        value = data.get(section)
        if not isinstance(value, dict):
            raise ValueError(f"{section} must be an object")
        for key in ("major", "minor"):
            if not isinstance(value.get(key), int) or value[key] < 0:
                raise ValueError(f"{section}.{key} must be a non-negative integer")
    profiles = data.get("capability_profiles")
    if not isinstance(profiles, dict):
        raise ValueError("capability_profiles must be an object")
    for profile_name in ("agent", "cardputer_firmware"):
        capabilities = profiles.get(profile_name)
        if (
            not isinstance(capabilities, list)
            or not capabilities
            or any(not isinstance(item, str) or not item for item in capabilities)
            or len(capabilities) != len(set(capabilities))
        ):
            raise ValueError(
                f"capability_profiles.{profile_name} must be a non-empty list of unique strings"
            )
    updates = data.get("updates")
    if not isinstance(updates, dict):
        raise ValueError("updates must be an object")
    if not isinstance(updates.get("sparkle_version"), str):
        raise ValueError("updates.sparkle_version must be a string")
    feed_url = updates.get("feed_url")
    if not isinstance(feed_url, str) or not feed_url.startswith("https://"):
        raise ValueError("updates.feed_url must be an HTTPS URL")
    public_key = updates.get("public_ed_key")
    if not isinstance(public_key, str) or len(public_key) != 44:
        raise ValueError("updates.public_ed_key must be a base64 Ed25519 public key")
    try:
        decoded_public_key = base64.b64decode(public_key, validate=True)
    except ValueError as exc:
        raise ValueError("updates.public_ed_key must be valid base64") from exc
    if len(decoded_public_key) != 32:
        raise ValueError("updates.public_ed_key must decode to 32 bytes")
    if data["release"] != data["mac_app"]["version"]:
        raise ValueError("release and mac_app.version must match")
    if data["mac_app"] != data["bridge_agent"]:
        raise ValueError("mac_app and bridge_agent version/build must match")
    return data


def _python(data: dict[str, Any]) -> str:
    agent_capabilities = "\n".join(
        f'    "{item}",' for item in data["capability_profiles"]["agent"]
    )
    firmware_capabilities = "\n".join(
        f'    "{item}",' for item in data["capability_profiles"]["cardputer_firmware"]
    )
    return f'''# Generated by tools/generate_versions.py. Do not edit.

RELEASE_VERSION = "{data["release"]}"
APP_VERSION = "{data["mac_app"]["version"]}"
APP_BUILD = {data["mac_app"]["build"]}
AGENT_VERSION = "{data["bridge_agent"]["version"]}"
AGENT_BUILD = {data["bridge_agent"]["build"]}
AGENT_API_MAJOR = {data["agent_api"]["major"]}
AGENT_API_MINOR = {data["agent_api"]["minor"]}
FIRMWARE_VERSION = "{data["firmware"]["version"]}"
MIN_FIRMWARE_VERSION = "{data["compatibility"]["min_firmware"]}"
DEVICE_PROTOCOL_MAJOR = {data["device_protocol"]["major"]}
DEVICE_PROTOCOL_MINOR = {data["device_protocol"]["minor"]}
CONFIG_SCHEMA = {data["config_schema"]}
SUPPORT_LEGACY_PROTOCOL_1 = {data["compatibility"]["legacy_protocol_1"]!r}
AGENT_CAPABILITIES = (
{agent_capabilities}
)
FIRMWARE_CAPABILITIES = (
{firmware_capabilities}
)
# Compatibility alias for callers that mean the server-side capability profile.
CAPABILITIES = AGENT_CAPABILITIES
'''


def _cpp(data: dict[str, Any]) -> str:
    capabilities = "\n".join(
        f'    "{item}",' for item in data["capability_profiles"]["cardputer_firmware"]
    )
    legacy = "true" if data["compatibility"]["legacy_protocol_1"] else "false"
    return f'''// Generated by tools/generate_versions.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace cardbridge {{

inline constexpr char kFirmwareVersion[] = "{data["firmware"]["version"]}";
inline constexpr uint32_t kFirmwareBuild = {data["firmware"]["build"]};
inline constexpr uint8_t kDeviceProtocolMajor = {data["device_protocol"]["major"]};
inline constexpr uint8_t kDeviceProtocolMinor = {data["device_protocol"]["minor"]};
inline constexpr bool kSupportLegacyProtocol1 = {legacy};
inline constexpr const char* kDeviceCapabilities[] = {{
{capabilities}
}};
inline constexpr size_t kDeviceCapabilityCount =
    sizeof(kDeviceCapabilities) / sizeof(kDeviceCapabilities[0]);

}}  // namespace cardbridge
'''


def _swift(data: dict[str, Any]) -> str:
    capabilities = ",\n".join(
        f'        "{item}"' for item in data["capability_profiles"]["agent"]
    )
    firmware_capabilities = ",\n".join(
        f'        "{item}"'
        for item in data["capability_profiles"]["cardputer_firmware"]
    )
    return f'''// Generated by tools/generate_versions.py. Do not edit.

enum GeneratedVersion {{
    static let release = "{data["release"]}"
    static let app = "{data["mac_app"]["version"]}"
    static let appBuild = {data["mac_app"]["build"]}
    static let agent = "{data["bridge_agent"]["version"]}"
    static let agentBuild = {data["bridge_agent"]["build"]}
    static let agentAPIMajor = {data["agent_api"]["major"]}
    static let agentAPIMinor = {data["agent_api"]["minor"]}
    static let deviceProtocolMajor = {data["device_protocol"]["major"]}
    static let deviceProtocolMinor = {data["device_protocol"]["minor"]}
    static let capabilities = [
{capabilities}
    ]
    static let firmwareCapabilities = [
{firmware_capabilities}
    ]
}}
'''


def _info_plist(data: dict[str, Any]) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>zh_CN</string>
    <key>CFBundleDisplayName</key>
    <string>Codex Deck</string>
    <key>CFBundleExecutable</key>
    <string>CardBridge</string>
    <key>CFBundleIdentifier</key>
    <string>com.voltwake.cardbridge</string>
    <key>CFBundleIconFile</key>
    <string>CardBridge</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>CardBridge</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>{data["mac_app"]["version"]}</string>
    <key>CFBundleVersion</key>
    <string>{data["mac_app"]["build"]}</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSBonjourServices</key>
    <array>
        <string>_cardbridge._tcp</string>
    </array>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSLocalNetworkUsageDescription</key>
    <string>Codex Deck 需要在局域网中发现并连接你的 Cardputer。</string>
    <key>SUEnableAutomaticChecks</key>
    <true/>
    <key>SUFeedURL</key>
    <string>{data["updates"]["feed_url"]}</string>
    <key>SUPublicEDKey</key>
    <string>{data["updates"]["public_ed_key"]}</string>
    <key>SUScheduledCheckInterval</key>
    <integer>86400</integer>
</dict>
</plist>
'''


def _agent_info_plist(data: dict[str, Any]) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>zh_CN</string>
    <key>CFBundleDisplayName</key>
    <string>Codex Deck Agent</string>
    <key>CFBundleExecutable</key>
    <string>CardBridgeAgent</string>
    <key>CFBundleIdentifier</key>
    <string>com.voltwake.cardbridge.agent</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>CardBridgeAgent</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>{data["bridge_agent"]["version"]}</string>
    <key>CFBundleVersion</key>
    <string>{data["bridge_agent"]["build"]}</string>
    <key>LSBackgroundOnly</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>NSBonjourServices</key>
    <array>
        <string>_cardbridge._tcp</string>
    </array>
    <key>NSLocalNetworkUsageDescription</key>
    <string>Codex Deck Agent 需要在局域网中发现并连接你的 Cardputer。</string>
</dict>
</plist>
'''


def _compatibility_json(data: dict[str, Any]) -> str:
    output = {
        "schema": 1,
        "release": data["release"],
        "mac_app": {
            **data["mac_app"],
            "minimum_macos": "13.0",
            "architectures": ["arm64"],
        },
        "bridge_agent": data["bridge_agent"],
        "firmware": data["firmware"],
        "agent_api": data["agent_api"],
        "device_protocol": data["device_protocol"],
        "minimum_firmware": data["compatibility"]["min_firmware"],
        "legacy_protocol_1": data["compatibility"]["legacy_protocol_1"],
        "capability_profiles": data["capability_profiles"],
    }
    return json.dumps(output, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def outputs(data: dict[str, Any]) -> dict[Path, str]:
    return {
        ROOT / "bridge" / "cardbridge" / "_generated_version.py": _python(data),
        ROOT / "src" / "generated_version.h": _cpp(data),
        ROOT / "macos" / "Shared" / "GeneratedVersion.swift": _swift(data),
        ROOT / "macos" / "App" / "Info.plist": _info_plist(data),
        ROOT / "macos" / "App" / "Agent-Info.plist": _agent_info_plist(data),
        ROOT / "release" / "compatibility.json": _compatibility_json(data),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate CardBridge version constants")
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    generated = outputs(_load())
    stale: list[Path] = []
    for path, content in generated.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"stale generated file: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
