#!/usr/bin/env python3
"""Convert a 240x135 RGB image into a flash-resident RGB565 UI asset."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


SCREEN_SIZE = (240, 135)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def emit(source: Path, output_dir: Path) -> None:
    image = Image.open(source).convert("RGB")
    if image.size != SCREEN_SIZE:
        raise SystemExit(
            f"{source}: expected {SCREEN_SIZE[0]}x{SCREEN_SIZE[1]}, "
            f"got {image.width}x{image.height}"
        )

    getter = getattr(image, "get_flattened_data", None)
    image_pixels = getter() if getter is not None else image.getdata()
    pixels = [rgb565(red, green, blue) for red, green, blue in image_pixels]
    header = """// Generated by tools/pack_ui_background.py; do not hand-edit.
#pragma once

#include <Arduino.h>

namespace cardbridge::ui_background_asset {

constexpr uint16_t kWidth = 240;
constexpr uint16_t kHeight = 135;
extern const uint16_t kPixels[kWidth * kHeight];

}  // namespace cardbridge::ui_background_asset
"""

    lines = [
        "// Generated by tools/pack_ui_background.py; do not hand-edit.",
        '#include "ui_background_asset.h"',
        "",
        "namespace cardbridge::ui_background_asset {",
        "",
        "const uint16_t kPixels[kWidth * kHeight] PROGMEM = {",
    ]
    for start in range(0, len(pixels), 16):
        values = ", ".join(f"0x{value:04x}" for value in pixels[start:start + 16])
        lines.append(f"    {values},")
    lines.extend([
        "};",
        "",
        "}  // namespace cardbridge::ui_background_asset",
        "",
    ])

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "ui_background_asset.h").write_text(header, encoding="utf-8")
    (output_dir / "ui_background_asset.cpp").write_text(
        "\n".join(lines), encoding="utf-8"
    )
    print(f"packed {image.width}x{image.height}: {len(pixels) * 2} RGB565 bytes")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("firmware/m5stack-cardputer-adv/src"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    emit(args.source, args.output_dir)


if __name__ == "__main__":
    main()
